import type { HardwareItem, SoftwareItem } from '@/types'

const hw = (file: string) => `/images/uses/hardware/${file}`
const sw = (file: string) => `/images/uses/software/${file}`
const swt = (light: string, dark: string) => ({
  light: sw(light),
  dark: sw(dark),
})

export const hardware: HardwareItem[] = [
  {
    name: 'MacBook Air 15"',
    description: 'M2 chip, 8GB RAM, 256GB SSD',
    url: 'https://support.apple.com/en-us/111346',
    image: hw('macbook-air.png'),
  },
  {
    name: 'Mac mini',
    description: 'M4 chip, 16GB RAM, 256GB SSD',
    url: 'https://support.apple.com/en-us/121555',
    image: hw('mac-mini.png'),
  },
  {
    name: 'ThinkCentre M70q',
    description: 'Intel i5, 32GB RAM, 1TB SSD, Proxmox VE',
    url: 'https://www.lenovo.com/in/en/p/desktops/thinkcentre/m-series-tiny/lenovo-thinkcentre-m70q-gen-5-tiny-intel/12tqcto1wwin1',
    image: hw('lenovo-server.png'),
  },
  {
    name: 'Samsung M7 Smart Monitor',
    description: 'White, 32-inch, 4K UHD smart monitor',
    url: 'https://www.samsung.com/in/monitors/smart/smart-monitor-m7-32-inch-smart-tv-apps-4k-uhd-ls32fm700uwxxl/',
    image: hw('smart-monitor.png'),
  },
  {
    name: 'Logitech MX Mechanical Mini',
    description: 'For Mac, Pale Gray, tactile quiet switches',
    url: 'https://www.logitech.com/products/keyboards/mx-mechanical-mini.html',
    image: hw('mx-mechanical-mini.png'),
  },
  {
    name: 'Logitech Signature M650',
    description: 'Off-white wireless mouse',
    url: 'https://www.logitech.com/products/mice/signature-m650.html',
    image: hw('m650-off-white.png'),
  },
  {
    name: 'Logitech Brio 300',
    description: 'Off-white USB webcam',
    url: 'https://www.logitech.com/products/webcams/brio-300-webcam.html',
    image: hw('brio-300.png'),
  },
  {
    name: 'Marshall Major V',
    description: 'Black wireless on-ear headphones',
    url: 'https://www.marshall.com/us/en/product/major-v',
    image: hw('major-v.png'),
  },
  {
    name: 'iPhone 16 Pro',
    description: 'Desert Titanium, 256GB',
    url: 'https://support.apple.com/en-us/111840',
    image: hw('iphone-16-pro.png'),
  },
  {
    name: 'iPad 10th Gen',
    description:
      'Silver, 128GB, Wi-Fi + Cellular, Apple Pencil, Magic Keyboard Folio',
    url: 'https://support.apple.com/en-us/111833',
    image: hw('ipad.png'),
  },
  {
    name: 'Apple Watch Series 9',
    description: '45mm, Starlight, Sport Loop',
    url: 'https://support.apple.com/en-us/121031',
    image: hw('apple-watch.png'),
  },
  {
    name: 'IKEA Lighting',
    description: 'IKEA MITTLED, TRADFRI driver with RODRET button',
    url: 'https://www.ikea.com/us/en/p/mittled-led-kitchen-cntrtp-lighting-strip-dimmable-white-10455434/',
    image: hw('mittled.png'),
  },
]

export const software: SoftwareItem[] = [
  {
    name: '1Password',
    description: 'Password manager',
    logo: swt('1password-light.svg', '1password-dark.svg'),
    url: 'https://1password.com',
    featured: true,
  },
  {
    name: 'Alcove',
    description: 'Notch dock utility',
    logo: sw('alcove.png'),
    url: 'https://tryalcove.com',
  },
  {
    name: 'Amphetamine',
    description: 'Keeps Mac awake',
    logo: sw('amphetamine.png'),
    url: 'https://apps.apple.com/app/amphetamine/id937984704',
  },
  {
    name: 'Antinote',
    description: 'Quick notes',
    logo: sw('antinote.png'),
    url: 'https://antinote.io',
  },
  {
    name: 'Bartender',
    description: 'Menu bar organizer',
    logo: sw('bartender.png'),
    url: 'https://www.macbartender.com',
  },
  {
    name: 'Beeper',
    description: 'Unified messaging',
    logo: sw('beeper.webp'),
    url: 'https://www.beeper.com',
  },
  {
    name: 'BetterDisplay',
    description: 'Display management',
    logo: sw('betterdisplay.png'),
    url: 'https://betterdisplay.pro',
  },
  {
    name: 'CleanShot X',
    description: 'Screen capture and recording',
    logo: sw('cleanshotx.png'),
    url: 'https://cleanshot.com',
  },
  {
    name: 'Claude Code',
    description: 'AI coding assistant',
    logo: sw('claude.svg'),
    url: 'https://www.anthropic.com/claude-code',
  },
  {
    name: 'Conductor',
    description: 'Utility app',
    logo: sw('conductor.png'),
    url: 'https://conductor.build',
  },
  {
    name: 'Craft',
    description: 'Notes and documents',
    logo: sw('craft.png'),
    url: 'https://www.craft.do',
  },
  {
    name: 'Dia',
    description: 'Browser',
    logo: sw('dia.png'),
    url: 'https://diabrowser.com',
  },
  {
    name: 'Downie',
    description: 'Video downloader',
    logo: sw('downie.png'),
    url: 'https://software.charliemonroe.net/downie/',
  },
  {
    name: 'Dropover',
    description: 'Drag and drop shelf',
    logo: sw('dropover.png'),
    url: 'https://dropoverapp.com',
  },
  {
    name: 'Ghostty',
    description: 'Terminal emulator',
    logo: sw('ghostty.svg'),
    url: 'https://ghostty.org',
  },
  {
    name: 'Goodnotes',
    description: 'Digital notebook',
    logo: sw('goodnotes.png'),
    url: 'https://www.goodnotes.com',
  },
  {
    name: 'IINA',
    description: 'Media player',
    logo: sw('iina.png'),
    url: 'https://iina.io',
  },
  {
    name: 'LookAway',
    description: 'Break reminders',
    logo: sw('lookaway.png'),
    url: 'https://lookaway.app',
  },
  {
    name: 'Loop',
    description: 'Window manager',
    logo: sw('loop.png'),
    url: 'https://github.com/MrKai77/Loop',
  },
  {
    name: 'Mole',
    description: 'Volume control per app',
    logo: sw('mole.png'),
    url: 'https://github.com/tw93/Mole',
  },
  {
    name: 'Notion',
    description: 'Notes and docs',
    logo: sw('notion.svg'),
    url: 'https://www.notion.com',
    featured: true,
  },
  {
    name: 'Notion Calendar',
    description: 'Calendar client',
    logo: sw('notion-calendar.webp'),
    url: 'https://www.notion.com/product/calendar',
  },
  {
    name: 'OpenCode',
    description: 'Coding assistant',
    logo: swt('opencode-light.svg', 'opencode-dark.svg'),
    url: 'https://opencode.ai',
  },
  {
    name: 'OrbStack',
    description: 'Containers and Linux VMs',
    logo: sw('orbstack.png'),
    url: 'https://orbstack.dev',
  },
  {
    name: 'Paste',
    description: 'Clipboard manager',
    logo: sw('paste.png'),
    url: 'https://pasteapp.io',
  },
  {
    name: 'Pictogram',
    description: 'Utility app',
    logo: sw('pictogram.png'),
    url: 'https://pictogramapp.com',
  },
  {
    name: 'PixelSnap',
    description: 'Screen measuring tool',
    logo: sw('pixelsnap.png'),
    url: 'https://pixelsnap.com',
  },
  {
    name: 'Raindrop.io',
    description: 'Bookmark manager',
    logo: sw('raindrop.svg'),
    url: 'https://raindrop.io',
  },
  {
    name: 'Raycast',
    description: 'Productivity launcher',
    logo: sw('raycast.svg'),
    url: 'https://raycast.com',
    featured: true,
  },
  {
    name: 'Spark Mail',
    description: 'Email client',
    logo: sw('spark-mail.png'),
    url: 'https://sparkmailapp.com',
  },
  {
    name: 'Spotify',
    description: 'Music streaming',
    logo: sw('spotify.svg'),
    url: 'https://spotify.com',
  },
  {
    name: 'Supercharge',
    description: 'Mac productivity utilities',
    logo: sw('supercharge.png'),
    url: 'https://sindresorhus.com/supercharge',
  },
  {
    name: 'Termius',
    description: 'SSH client',
    logo: sw('termius.webp'),
    url: 'https://termius.com',
  },
  {
    name: 'Typefully',
    description: 'Writing and scheduling tool',
    logo: sw('typefully.png'),
    url: 'https://typefully.com',
  },
  {
    name: 'UTM',
    description: 'Virtual machines',
    logo: sw('utm.png'),
    url: 'https://mac.getutm.app',
  },
  {
    name: 'Vesktop',
    description: 'Discord client',
    logo: sw('vesktop.svg'),
    url: 'https://vesktop.dev',
  },
  {
    name: 'Visual Studio Code',
    description: 'Code editor',
    logo: sw('vscode.svg'),
    url: 'https://code.visualstudio.com',
    featured: true,
  },
  {
    name: 'Warp',
    description: 'Terminal',
    logo: sw('warp.png'),
    url: 'https://warp.dev',
  },
  {
    name: 'Wispr Flow',
    description: 'Voice dictation',
    logo: sw('wispr-flow.webp'),
    url: 'https://wisprflow.ai',
  },
  {
    name: 'Yaak',
    description: 'API client',
    logo: sw('yaak.png'),
    url: 'https://yaak.app',
  },
]
