import type { HardwareItem, SoftwareItem } from '@/types'

export const hardware: HardwareItem[] = [
  {
    name: 'MacBook Air 15"',
    description: 'M2 chip, 8GB RAM, 256GB SSD',
    url: 'https://support.apple.com/en-us/111346',
    image: '/images/uses/hardware/macbook-air.png',
  },
  {
    name: 'Mac mini',
    description: 'M4 chip, 16GB RAM, 256GB SSD',
    url: 'https://support.apple.com/en-us/121555',
    image: '/images/uses/hardware/mac-mini.png',
  },
  {
    name: 'ThinkCentre M70q',
    description: 'Intel i5, 32GB RAM, 1TB SSD, Proxmox VE',
    url: 'https://www.lenovo.com/in/en/p/desktops/thinkcentre/m-series-tiny/lenovo-thinkcentre-m70q-gen-5-tiny-intel/12tqcto1wwin1',
    image: '/images/uses/hardware/lenovo-server.png',
  },
  {
    name: 'Samsung M7 Smart Monitor',
    description: 'White, 32-inch, 4K UHD smart monitor',
    url: 'https://www.samsung.com/in/monitors/smart/smart-monitor-m7-32-inch-smart-tv-apps-4k-uhd-ls32fm700uwxxl/',
    image: '/images/uses/hardware/smart-monitor.png',
  },
  {
    name: 'Logitech MX Mechanical Mini',
    description: 'For Mac, Pale Gray, tactile quiet switches',
    url: 'https://www.logitech.com/products/keyboards/mx-mechanical-mini.html',
    image: '/images/uses/hardware/mx-mechanical-mini.png',
  },
  {
    name: 'Logitech Signature M650',
    description: 'Off-white wireless mouse',
    url: 'https://www.logitech.com/products/mice/signature-m650.html',
    image: '/images/uses/hardware/m650-off-white.png',
  },
  {
    name: 'Logitech Brio 300',
    description: 'Off-white USB webcam',
    url: 'https://www.logitech.com/products/webcams/brio-300-webcam.html',
    image: '/images/uses/hardware/brio-300.png',
  },
  {
    name: 'Marshall Major V',
    description: 'Black wireless on-ear headphones',
    url: 'https://www.marshall.com/us/en/product/major-v',
    image: '/images/uses/hardware/major-v.png',
  },
  {
    name: 'iPhone 16 Pro',
    description: 'Desert Titanium, 256GB',
    url: 'https://support.apple.com/en-us/111840',
    image: '/images/uses/hardware/iphone-16-pro.png',
  },
  {
    name: 'iPad 10th Gen',
    description:
      'Silver, 128GB, Wi-Fi + Cellular, Apple Pencil, Magic Keyboard Folio',
    url: 'https://support.apple.com/en-us/111833',
    image: '/images/uses/hardware/ipad.png',
  },
  {
    name: 'Apple Watch Series 9',
    description: '45mm, Starlight, Sport Loop',
    url: 'https://support.apple.com/en-us/121031',
    image: '/images/uses/hardware/apple-watch.png',
  },
  {
    name: 'IKEA Lighting',
    description: 'IKEA MITTLED, TRADFRI driver with RODRET button',
    url: 'https://www.ikea.com/us/en/p/mittled-led-kitchen-cntrtp-lighting-strip-dimmable-white-10455434/',
    image: '/images/uses/hardware/mittled.png',
  },
]

export const software: SoftwareItem[] = [
  {
    name: '1Password',
    description: 'Password manager',
    logo: {
      light: '/images/uses/software/1password-light.svg',
      dark: '/images/uses/software/1password-dark.svg',
    },
    url: 'https://1password.com',
    featured: true,
  },
  {
    name: 'Alcove',
    description: 'Notch dock utility',
    logo: '/images/uses/software/alcove.png',
    url: 'https://tryalcove.com',
  },
  {
    name: 'Amphetamine',
    description: 'Keeps Mac awake',
    logo: '/images/uses/software/amphetamine.png',
    url: 'https://apps.apple.com/app/amphetamine/id937984704',
  },
  {
    name: 'Antinote',
    description: 'Quick notes',
    logo: '/images/uses/software/antinote.png',
    url: 'https://antinote.io',
  },
  {
    name: 'Bartender',
    description: 'Menu bar organizer',
    logo: '/images/uses/software/bartender.png',
    url: 'https://www.macbartender.com',
  },
  {
    name: 'Beeper',
    description: 'Unified messaging',
    logo: '/images/uses/software/beeper.webp',
    url: 'https://www.beeper.com',
  },
  {
    name: 'BetterDisplay',
    description: 'Display management',
    logo: '/images/uses/software/betterdisplay.png',
    url: 'https://betterdisplay.pro',
  },
  {
    name: 'CleanShot X',
    description: 'Screen capture and recording',
    logo: '/images/uses/software/cleanshotx.png',
    url: 'https://cleanshot.com',
  },
  {
    name: 'Claude Code',
    description: 'AI coding assistant',
    logo: '/images/uses/software/claude.svg',
    url: 'https://www.anthropic.com/claude-code',
  },
  {
    name: 'Conductor',
    description: 'Utility app',
    logo: '/images/uses/software/conductor.png',
    url: 'https://conductor.build',
  },
  {
    name: 'Craft',
    description: 'Notes and documents',
    logo: '/images/uses/software/craft.png',
    url: 'https://www.craft.do',
  },
  {
    name: 'Dia',
    description: 'Browser',
    logo: '/images/uses/software/dia.png',
    url: 'https://diabrowser.com',
  },
  {
    name: 'Downie',
    description: 'Video downloader',
    logo: '/images/uses/software/downie.png',
    url: 'https://software.charliemonroe.net/downie/',
  },
  {
    name: 'Dropover',
    description: 'Drag and drop shelf',
    logo: '/images/uses/software/dropover.png',
    url: 'https://dropoverapp.com',
  },
  {
    name: 'Ghostty',
    description: 'Terminal emulator',
    logo: '/images/uses/software/ghostty.svg',
    url: 'https://ghostty.org',
  },
  {
    name: 'Goodnotes',
    description: 'Digital notebook',
    logo: '/images/uses/software/goodnotes.png',
    url: 'https://www.goodnotes.com',
  },
  {
    name: 'IINA',
    description: 'Media player',
    logo: '/images/uses/software/iina.png',
    url: 'https://iina.io',
  },
  {
    name: 'LookAway',
    description: 'Break reminders',
    logo: '/images/uses/software/lookaway.png',
    url: 'https://lookaway.app',
  },
  {
    name: 'Loop',
    description: 'Window manager',
    logo: '/images/uses/software/loop.png',
    url: 'https://github.com/MrKai77/Loop',
  },
  {
    name: 'Mole',
    description: 'Volume control per app',
    logo: '/images/uses/software/mole.png',
    url: 'https://github.com/tw93/Mole',
  },
  {
    name: 'Notion',
    description: 'Notes and docs',
    logo: '/images/uses/software/notion.svg',
    url: 'https://www.notion.com',
    featured: true,
  },
  {
    name: 'Notion Calendar',
    description: 'Calendar client',
    logo: '/images/uses/software/notion-calendar.webp',
    url: 'https://www.notion.com/product/calendar',
  },
  {
    name: 'OpenCode',
    description: 'Coding assistant',
    logo: {
      light: '/images/uses/software/opencode-light.svg',
      dark: '/images/uses/software/opencode-dark.svg',
    },
    url: 'https://opencode.ai',
  },
  {
    name: 'OrbStack',
    description: 'Containers and Linux VMs',
    logo: '/images/uses/software/orbstack.png',
    url: 'https://orbstack.dev',
  },
  {
    name: 'Paste',
    description: 'Clipboard manager',
    logo: '/images/uses/software/paste.png',
    url: 'https://pasteapp.io',
  },
  {
    name: 'Pictogram',
    description: 'Utility app',
    logo: '/images/uses/software/pictogram.png',
    url: 'https://pictogramapp.com',
  },
  {
    name: 'PixelSnap',
    description: 'Screen measuring tool',
    logo: '/images/uses/software/pixelsnap.png',
    url: 'https://pixelsnap.com',
  },
  {
    name: 'Raindrop.io',
    description: 'Bookmark manager',
    logo: '/images/uses/software/raindrop.svg',
    url: 'https://raindrop.io',
  },
  {
    name: 'Raycast',
    description: 'Productivity launcher',
    logo: '/images/uses/software/raycast.svg',
    url: 'https://raycast.com',
    featured: true,
  },
  {
    name: 'Spark Mail',
    description: 'Email client',
    logo: '/images/uses/software/spark-mail.png',
    url: 'https://sparkmailapp.com',
  },
  {
    name: 'Spotify',
    description: 'Music streaming',
    logo: '/images/uses/software/spotify.svg',
    url: 'https://spotify.com',
  },
  {
    name: 'Supercharge',
    description: 'Mac productivity utilities',
    logo: '/images/uses/software/supercharge.png',
    url: 'https://sindresorhus.com/supercharge',
  },
  {
    name: 'Termius',
    description: 'SSH client',
    logo: '/images/uses/software/termius.webp',
    url: 'https://termius.com',
  },
  {
    name: 'Typefully',
    description: 'Writing and scheduling tool',
    logo: '/images/uses/software/typefully.png',
    url: 'https://typefully.com',
  },
  {
    name: 'UTM',
    description: 'Virtual machines',
    logo: '/images/uses/software/utm.png',
    url: 'https://mac.getutm.app',
  },
  {
    name: 'Vesktop',
    description: 'Discord client',
    logo: '/images/uses/software/vesktop.svg',
    url: 'https://vesktop.dev',
  },
  {
    name: 'Visual Studio Code',
    description: 'Code editor',
    logo: '/images/uses/software/vscode.svg',
    url: 'https://code.visualstudio.com',
    featured: true,
  },
  {
    name: 'Warp',
    description: 'Terminal',
    logo: '/images/uses/software/warp.png',
    url: 'https://warp.dev',
  },
  {
    name: 'Wispr Flow',
    description: 'Voice dictation',
    logo: '/images/uses/software/wispr-flow.webp',
    url: 'https://wisprflow.ai',
  },
  {
    name: 'Yaak',
    description: 'API client',
    logo: '/images/uses/software/yaak.png',
    url: 'https://yaak.app',
  },
]
