'use client'

import { useTheme } from 'next-themes'
import { use, useEffect, useId, useRef, useState } from 'react'

export function Mermaid({ chart }: { chart: string }) {
  const mountedRef = useRef(false)
  const [, forceUpdate] = useState(0)

  useEffect(() => {
    if (!mountedRef.current) {
      mountedRef.current = true
      forceUpdate((n) => n + 1)
    }
  }, [])

  return (
    // suppressHydrationWarning prevents the hydration mismatch flash
    // caused by server rendering nothing and client rendering the chart
    <div suppressHydrationWarning>
      {mountedRef.current ? <MermaidContent chart={chart} /> : null}
    </div>
  )
}

const cache = new Map<string, Promise<unknown>>()

function cachePromise<T>(
  key: string,
  setPromise: () => Promise<T>
): Promise<T> {
  const cached = cache.get(key)
  if (cached) {
    return cached as Promise<T>
  }

  const promise = setPromise()
  cache.set(key, promise)
  return promise
}

function MermaidContent({ chart }: { chart: string }) {
  const id = useId()
  const { resolvedTheme } = useTheme()
  const { default: mermaid } = use(
    cachePromise('mermaid', () => import('mermaid'))
  )

  mermaid.initialize({
    startOnLoad: false,
    securityLevel: 'loose',
    fontFamily: 'inherit',
    themeCSS: 'margin: 1.5rem auto 0;',
    theme: resolvedTheme === 'dark' ? 'dark' : 'default',
  })

  const { svg, bindFunctions } = use(
    cachePromise(`${chart}-${resolvedTheme}`, () =>
      mermaid.render(id, chart.replaceAll('\\n', '\n'))
    )
  )

  return (
    <div
      // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by the trusted mermaid library
      dangerouslySetInnerHTML={{ __html: svg }}
      ref={(container) => {
        if (container) {
          bindFunctions?.(container)
        }
      }}
    />
  )
}
