import {
  AiChat02Icon,
  AiChemistry01Icon,
  Alert02Icon,
  ArtificialIntelligence04Icon,
  AtIcon,
  BotIcon,
  BrainIcon,
  Briefcase02Icon,
  BubbleChatIcon,
  Calendar03Icon,
  CallIcon,
  Cancel01Icon,
  CheckmarkBadge02Icon,
  CheckmarkCircle01Icon,
  ChipIcon,
  CodeIcon,
  Copy01Icon,
  CopyCheckIcon,
  CreditCardIcon,
  Delete02Icon,
  DollarCircleIcon,
  Download01Icon,
  EraserIcon,
  StarIcon as FeaturedIcon,
  File01Icon,
  File02Icon,
  Globe02Icon,
  HelpCircleIcon,
  Home01Icon,
  Image01Icon,
  InformationCircleIcon,
  LaptopIcon,
  Layers01Icon,
  Link01Icon,
  Loading03Icon,
  Login03Icon,
  Logout03Icon,
  Mail01Icon,
  Menu01Icon,
  Message01Icon,
  Moon02Icon,
  MoreHorizontalCircle01Icon,
  MoreVerticalIcon,
  MultiplicationSignCircleIcon,
  NewsIcon,
  Notebook01Icon,
  PencilEdit01Icon,
  Pizza01Icon,
  PlusSignIcon,
  QuoteUpIcon,
  Redo03Icon,
  RefreshIcon,
  RssIcon,
  Search01Icon,
  SentIcon,
  Settings01Icon,
  Share08Icon,
  SmartPhone01Icon,
  SourceCodeSquareIcon,
  SquareIcon,
  Sun03Icon,
  Tablet01Icon,
  Tag01Icon,
  TagsIcon,
  Tick02Icon,
  Tv01Icon,
  Tv02Icon,
  UnavailableIcon,
  Undo03Icon,
  UserBlock01Icon,
  UserIcon,
  Wrench01Icon,
} from '@hugeicons/core-free-icons'
import { HugeiconsIcon } from '@hugeicons/react'
import {
  CommentIcon,
  FeedPublicIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitPullRequestIcon,
  IssueClosedIcon,
  IssueOpenedIcon,
  IssueReopenedIcon,
  IssueTrackedByIcon,
  IssueTracksIcon,
  MarkGithubIcon,
  RepoForkedIcon,
  RepoIcon,
  StarIcon,
  TagIcon,
} from '@primer/octicons-react'
import {
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CornerDownLeft,
  type LucideIcon,
  PawPrintIcon,
} from 'lucide-react'
import type { ComponentProps } from 'react'
import {
  ClaudeIcon,
  CursorIcon,
  GitHubIcon,
  GoogleIcon,
  GrokIcon,
  LinkedInIcon,
  MarkdownIcon,
  OpenAIIcon,
  SciraIcon,
  V0Icon,
  XIcon,
  YouTubeIcon,
} from './brands'
import type { IconProps, SvgIcon } from './utils'
import { getSvgSizeProps } from './utils'

export type { Icon } from './utils'

type HugeIconDefinition = ComponentProps<typeof HugeiconsIcon>['icon']

const hugeIcon = (icon: HugeIconDefinition): SvgIcon => {
  const Icon = ({ height, size, strokeWidth, width, ...props }: IconProps) => {
    const parsedStrokeWidth =
      typeof strokeWidth === 'string'
        ? Number.parseFloat(strokeWidth)
        : strokeWidth
    const resolvedStrokeWidth =
      typeof parsedStrokeWidth === 'number' &&
      Number.isFinite(parsedStrokeWidth)
        ? parsedStrokeWidth
        : 2

    return (
      <HugeiconsIcon
        {...props}
        icon={icon}
        strokeWidth={resolvedStrokeWidth}
        {...getSvgSizeProps({ height, size, width })}
      />
    )
  }

  return Icon
}

const lucideIcon = (Icon: LucideIcon): SvgIcon => {
  const Lucide = ({ height, size, width, ...props }: IconProps) => (
    <Icon {...getSvgSizeProps({ height, size, width })} {...props} />
  )

  return Lucide
}

export const Icons = {
  logo: hugeIcon(CodeIcon),
  close: hugeIcon(Cancel01Icon),
  menu: hugeIcon(Menu01Icon),
  code: hugeIcon(CodeIcon),
  codeXml: hugeIcon(SourceCodeSquareIcon),
  bot: hugeIcon(BotIcon),
  cpu: hugeIcon(ChipIcon),
  flask: hugeIcon(AiChemistry01Icon),
  work: hugeIcon(Briefcase02Icon),
  blog: hugeIcon(Notebook01Icon),
  pencil: hugeIcon(PencilEdit01Icon),
  copied: hugeIcon(CopyCheckIcon),
  success: hugeIcon(CheckmarkCircle01Icon),
  messageSquare: hugeIcon(Message01Icon),
  ai: hugeIcon(ArtificialIntelligence04Icon),
  aiChat: hugeIcon(AiChat02Icon),
  spinner: hugeIcon(Loading03Icon),
  atSign: hugeIcon(AtIcon),
  globe: hugeIcon(Globe02Icon),
  chevronLeft: lucideIcon(ChevronLeft),
  chevronRight: lucideIcon(ChevronRight),
  trash: hugeIcon(Delete02Icon),
  tags: hugeIcon(TagsIcon),
  tag: hugeIcon(Tag01Icon),
  share: hugeIcon(Share08Icon),
  posts: hugeIcon(NewsIcon),
  post: hugeIcon(File02Icon),
  page: hugeIcon(File01Icon),
  media: hugeIcon(Image01Icon),
  settings: hugeIcon(Settings01Icon),
  billing: hugeIcon(CreditCardIcon),
  ellipsis: hugeIcon(MoreVerticalIcon),
  add: hugeIcon(PlusSignIcon),
  logIn: hugeIcon(Login03Icon),
  logOut: hugeIcon(Logout03Icon),
  warning: hugeIcon(Alert02Icon),
  user: hugeIcon(UserIcon),
  arrowRight: lucideIcon(ArrowRight),
  arrowLeft: lucideIcon(ArrowLeft),
  arrowUp: lucideIcon(ArrowUp),
  arrowDown: lucideIcon(ArrowDown),
  arrowUpLeft: lucideIcon(ArrowUpLeft),
  help: hugeIcon(HelpCircleIcon),
  pizza: hugeIcon(Pizza01Icon),
  sun: hugeIcon(Sun03Icon),
  moon: hugeIcon(Moon02Icon),
  laptop: hugeIcon(LaptopIcon),
  home: hugeIcon(Home01Icon),
  info: hugeIcon(InformationCircleIcon),
  arrowUpRight: lucideIcon(ArrowUpRight),
  arrowDownLeft: lucideIcon(ArrowDownLeft),
  arrowDownRight: lucideIcon(ArrowDownRight),
  chevronDown: lucideIcon(ChevronDown),
  chevronUp: lucideIcon(ChevronUp),
  copy: hugeIcon(Copy01Icon),
  cornerDownLeft: lucideIcon(CornerDownLeft),
  messageCircle: hugeIcon(BubbleChatIcon),
  mail: hugeIcon(Mail01Icon),
  send: hugeIcon(SentIcon),
  pricing: hugeIcon(DollarCircleIcon),
  phone: hugeIcon(CallIcon),
  calendar: hugeIcon(Calendar03Icon),
  download: hugeIcon(Download01Icon),
  search: hugeIcon(Search01Icon),
  layers: hugeIcon(Layers01Icon),
  desktop: hugeIcon(Tv02Icon),
  mobile: hugeIcon(SmartPhone01Icon),
  tablet: hugeIcon(Tablet01Icon),
  tv: hugeIcon(Tv01Icon),
  link: hugeIcon(Link01Icon),
  brain: hugeIcon(BrainIcon),
  wrench: hugeIcon(Wrench01Icon),
  quote: hugeIcon(QuoteUpIcon),
  refresh: hugeIcon(RefreshIcon),
  square: hugeIcon(SquareIcon),
  undo: hugeIcon(Undo03Icon),
  redo: hugeIcon(Redo03Icon),
  eraser: hugeIcon(EraserIcon),
  moreHorizontal: hugeIcon(MoreHorizontalCircle01Icon),
  error: hugeIcon(MultiplicationSignCircleIcon),
  verified: hugeIcon(CheckmarkCircle01Icon),
  verifiedAdmin: hugeIcon(CheckmarkBadge02Icon),
  featured: hugeIcon(FeaturedIcon),
  ban: hugeIcon(UnavailableIcon),
  userBlocked: hugeIcon(UserBlock01Icon),
  pawPrint: lucideIcon(PawPrintIcon),
  check: hugeIcon(Tick02Icon),
  rss: hugeIcon(RssIcon),
  // Primer Octicons (GitHub activity feed)
  githubMark: MarkGithubIcon,
  gitCommit: GitCommitIcon,
  gitPullRequest: GitPullRequestIcon,
  issueClosed: IssueClosedIcon,
  issueOpened: IssueOpenedIcon,
  issueReopened: IssueReopenedIcon,
  issueTrackedBy: IssueTrackedByIcon,
  issueTracks: IssueTracksIcon,
  comment: CommentIcon,
  feedPublic: FeedPublicIcon,
  gitBranch: GitBranchIcon,
  repo: RepoIcon,
  repoForked: RepoForkedIcon,
  star: StarIcon,
  gitTag: TagIcon,
  // Brand / platform icons
  github: GitHubIcon,
  google: GoogleIcon,
  x: XIcon,
  linkedin: LinkedInIcon,
  youtube: YouTubeIcon,
  openai: OpenAIIcon,
  claude: ClaudeIcon,
  grok: GrokIcon,
  cursor: CursorIcon,
  scira: SciraIcon,
  markdown: MarkdownIcon,
  v0: V0Icon,
}
