// Minimal - generated by @web-kits/audio.
// Keep this as the source of truth for subtle UI feedback sounds.
import type { SoundDefinition, SoundPatch } from '@web-kits/audio'

export const tap: SoundDefinition = {
  envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
  gain: 0.08,
  source: { frequency: 1200, type: 'sine' },
}

export const click: SoundDefinition = {
  envelope: { attack: 0, decay: 0.015, release: 0.005, sustain: 0 },
  gain: 0.1,
  source: { frequency: 800, type: 'sine' },
}

export const keyPress: SoundDefinition = {
  envelope: { attack: 0, decay: 0.01, release: 0.003, sustain: 0 },
  gain: 0.06,
  source: { frequency: 1100, type: 'sine' },
}

export const toggleOn: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.02, release: 0.006, sustain: 0 },
      gain: 0.08,
      source: { frequency: 880, type: 'sine' },
    },
    {
      delay: 0.03,
      envelope: { attack: 0, decay: 0.02, release: 0.006, sustain: 0 },
      gain: 0.07,
      source: { frequency: 1320, type: 'sine' },
    },
  ],
}

export const toggleOff: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.02, release: 0.006, sustain: 0 },
      gain: 0.08,
      source: { frequency: 1320, type: 'sine' },
    },
    {
      delay: 0.03,
      envelope: { attack: 0, decay: 0.02, release: 0.006, sustain: 0 },
      gain: 0.07,
      source: { frequency: 880, type: 'sine' },
    },
  ],
}

export const checkbox: SoundDefinition = {
  envelope: { attack: 0, decay: 0.018, release: 0.005, sustain: 0 },
  gain: 0.09,
  source: { frequency: 1000, type: 'sine' },
}

export const select: SoundDefinition = {
  envelope: { attack: 0, decay: 0.02, release: 0.006, sustain: 0 },
  gain: 0.08,
  source: { frequency: 1100, type: 'sine' },
}

export const deselect: SoundDefinition = {
  envelope: { attack: 0, decay: 0.018, release: 0.005, sustain: 0 },
  gain: 0.06,
  source: { frequency: 900, type: 'sine' },
}

export const hover: SoundDefinition = {
  envelope: { attack: 0, decay: 0.01, release: 0.004, sustain: 0 },
  gain: 0.04,
  source: { frequency: 1300, type: 'sine' },
}

export const tabSwitch: SoundDefinition = {
  envelope: { attack: 0, decay: 0.015, release: 0.005, sustain: 0 },
  gain: 0.07,
  source: { frequency: 1050, type: 'sine' },
}

export const expand: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
  gain: 0.06,
  source: { frequency: { end: 1000, start: 800 }, type: 'sine' },
}

export const collapse: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
  gain: 0.06,
  source: { frequency: { end: 800, start: 1000 }, type: 'sine' },
}

export const pageEnter: SoundDefinition = {
  envelope: { attack: 0.003, decay: 0.04, release: 0.015, sustain: 0 },
  gain: 0.05,
  source: { frequency: { end: 900, start: 700 }, type: 'sine' },
}

export const pageExit: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.015, sustain: 0 },
  gain: 0.04,
  source: { frequency: { end: 700, start: 900 }, type: 'sine' },
}

export const success: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
      gain: 0.1,
      source: { frequency: 523, type: 'sine' },
    },
    {
      delay: 0.06,
      envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
      gain: 0.08,
      source: { frequency: 784, type: 'sine' },
    },
  ],
}

export const error: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
      gain: 0.12,
      source: { frequency: 300, type: 'sine' },
    },
    {
      delay: 0.01,
      envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
      gain: 0.1,
      source: { frequency: 280, type: 'sine' },
    },
  ],
}

export const warning: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.03, release: 0.01, sustain: 0 },
      gain: 0.1,
      source: { frequency: 440, type: 'sine' },
    },
    {
      delay: 0.008,
      envelope: { attack: 0, decay: 0.03, release: 0.01, sustain: 0 },
      gain: 0.08,
      source: { frequency: 466, type: 'sine' },
    },
  ],
}

export const notification: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.05, release: 0.02, sustain: 0 },
      gain: 0.1,
      source: { frequency: 660, type: 'sine' },
    },
    {
      delay: 0.08,
      envelope: { attack: 0, decay: 0.04, release: 0.015, sustain: 0 },
      gain: 0.08,
      source: { frequency: 880, type: 'sine' },
    },
  ],
}

export const info: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.015, sustain: 0 },
  gain: 0.08,
  source: { frequency: 880, type: 'sine' },
}

export const copy: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
      gain: 0.08,
      source: { frequency: 1000, type: 'sine' },
    },
    {
      delay: 0.035,
      envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
      gain: 0.07,
      source: { frequency: 1200, type: 'sine' },
    },
  ],
}

export const send: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
  gain: 0.08,
  source: { frequency: { end: 1000, start: 600 }, type: 'sine' },
}

export const deleteSound: SoundDefinition = {
  envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
  gain: 0.1,
  source: { frequency: { end: 250, start: 500 }, type: 'sine' },
}

export const undo: SoundDefinition = {
  envelope: { attack: 0, decay: 0.035, release: 0.01, sustain: 0 },
  gain: 0.07,
  source: { frequency: { end: 600, start: 800 }, type: 'sine' },
}

export const pop: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
  gain: 0.1,
  source: { frequency: { end: 200, start: 400 }, type: 'sine' },
}

export const swoosh: SoundDefinition = {
  envelope: { attack: 0.005, decay: 0.04, release: 0.015, sustain: 0 },
  gain: 0.05,
  source: { frequency: { end: 1400, start: 600 }, type: 'sine' },
}

export const slide: SoundDefinition = {
  envelope: { attack: 0.003, decay: 0.035, release: 0.012, sustain: 0 },
  gain: 0.05,
  source: { frequency: { end: 1100, start: 800 }, type: 'sine' },
}

export const minimalPatch: SoundPatch = {
  author: 'Raphael Salaja',
  description:
    'An ultra-clean sine-based palette for quiet, transparent UI feedback, made for products that prioritize subtlety, restraint, and smooth interaction cues over expressive flourish.',
  name: 'Minimal',
  sounds: {
    checkbox,
    click,
    collapse,
    copy,
    delete: deleteSound,
    deselect,
    error,
    expand,
    hover,
    info,
    'key-press': keyPress,
    notification,
    'page-enter': pageEnter,
    'page-exit': pageExit,
    pop,
    select,
    send,
    slide,
    success,
    swoosh,
    'tab-switch': tabSwitch,
    tap,
    'toggle-off': toggleOff,
    'toggle-on': toggleOn,
    undo,
    warning,
  },
  version: '1.0.0',
}
